version: '3'

services:
  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
      - "443:443"

  web:
    build: ./web
    expose:
      - "80"
    volumes:
      - ./web/htdocs/:/usr/local/apache2/htdocs/
    depends_on:
      - reverse-proxy
